import re
from typing import List


class SanskritGrammar:
    """
    The Structural Engine (Left Brain Foundation).

    Implements Paninian rules (Sandhi, Vibhakti) to structure the
    stream of consciousness generated by the Right Brain.
    """

    def __init__(self):
        # Basic Vowel Sandhi Rules (Dirgha Sandhi, Guna Sandhi)
        # a/ā + a/ā -> ā
        # a/ā + i/ī -> e
        # a/ā + u/ū -> o
        self.sandhi_rules = {
            r'(a|ā)\s+(a|ā)': 'ā',
            r'(a|ā)\s+(i|ī)': 'e',
            r'(a|ā)\s+(u|ū)': 'o',
            r'(i|ī)\s+(a|ā)': 'ya', # Yan Sandhi
            r'(u|ū)\s+(a|ā)': 'va', # Yan Sandhi
            # Visarga Sandhi (simplified)
            r'ah\s+([gdjbvmnylrh])': r'o \1', # ah + voiced -> o
            r'ah\s+([a])': r'o \1', # ah + a -> o '
        }

        # Basic Vibhakti (Case) Endings for 'a' ending nouns (masculine)
        # Concept -> Nominative (Agent), Accusative (Object), etc.
        self.vibhakti_map = {
            'agent': 'ah',    # Rama -> Ramah (Nominative Sing.)
            'object': 'am',   # Rama -> Ramam (Accusative Sing.)
            'instrument': 'ena', # Rama -> Ramena (Instrumental Sing.)
            'source': 'at',   # Rama -> Ramat (Ablative Sing.)
            'relation': 'asya', # Rama -> Ramasya (Genitive Sing.)
            'location': 'e',  # Rama -> Rame (Locative Sing.)
        }

    def apply_sandhi(self, text: str) -> str:
        """
        Applies phonetic fusion rules to smooth the stream of consciousness.
        """
        refined_text = text
        for pattern, replacement in self.sandhi_rules.items():
            refined_text = re.sub(pattern, replacement, refined_text, flags=re.IGNORECASE)
        return refined_text

    def apply_vibhakti(self, word: str, role: str) -> str:
        """
        Applies case endings based on thematic role (Karaka).
        """
        if role in self.vibhakti_map:
            # Very simplified: Assume 'a' stem for now
            if word.endswith('a'):
                return word[:-1] + self.vibhakti_map[role]
            else:
                return word + self.vibhakti_map[role] # Fallback
        return word

    def structure_thought(self, trajectory: List[str]) -> str:
        """
        Takes a raw sequence of concepts (Right Brain output) and
        structures it into a coherent sentence using Grammar.
        """
        # 1. Identify Roles (Heuristic for now)
        # First concept = Agent (Kartru)
        # Last concept = Action (Kriya)
        # Middle = Object/Instrument

        if not trajectory:
            return ""

        # Dedup consecutive duplicates (e.g., "safety", "safety" -> "safety")
        refined_trajectory = []
        if trajectory:
            refined_trajectory.append(trajectory[0])
            for i in range(1, len(trajectory)):
                if trajectory[i] != trajectory[i-1]:
                    refined_trajectory.append(trajectory[i])

        trajectory = refined_trajectory
        if not trajectory:
            return ""

        structured_words = []

        # Subject (Agent)
        subject = trajectory[0]
        structured_words.append(self.apply_vibhakti(subject, 'agent'))

        # Middle (Objects/Relations)
        for word in trajectory[1:-1]:
            # Default to Object for now
            structured_words.append(self.apply_vibhakti(word, 'object'))

        # Action (Verb) - Leave raw or apply verb ending
        if len(trajectory) > 1:
            action = trajectory[-1]
            structured_words.append(action + "ti") # Present tense singular

        # Join
        raw_sentence = " ".join(structured_words)

        # Apply Sandhi
        final_sentence = self.apply_sandhi(raw_sentence)

        return final_sentence
